### ISSUE TITLE
[testnet] Fee estimation is wrong

### ISSUE THREAD

**Issue by OliverOffing** [nunchuk-io/nunchuk-android#12]
The wallet is suggesting a high fee, which I must assume means it's not observing the testnet network as I have specified in the settings. Testnet fees are low (1sat/vB max) right now but I can't even override it in Nunchuk as it tells me "fee can't be lower than minimum."

**Comment by hugohn** [comment]
We'll take a look. Thanks @OliverOffing for reporting.

**Comment by JayceLuong** [comment]
We made a fix in the latest version, I think we can close it
