### ISSUE TITLE
[FEATURE REQUEST] increase gap limit (BTCpay server compatibility)

### ISSUE THREAD

**Issue by twofaktor** [nunchuk-io/nunchuk-android#13]
As a privacy measure, BTCpay does not reuse addresses but doesn't choose consecutive addresses, this means that when you import into Nunchuck a wallet that has been used by the BTCpay server, it does not show all UTXOS or fail when you try to import a PSBT generated by Sparrow with UTXOS out of scope of Nunchuk (Sparrow already integrates the limit gap). 

Nunchuck fails or doesn't show all UTXOS. This becomes an especially important problem in multi-signature wallets to be able to speed up the signatures and be able to do it, especially from the mobile version.

Do you have in the roadmap to incorporate this feature?

Thanks
issue already opened for the desktop version: https://github.com/nunchuk-io/nunchuk-desktop/issues/37
ref of other requests: https://github.com/BlueWallet/BlueWallet/issues/3398

**Comment by JayceLuong** [comment]
This feature is available in the latest version

**Comment by twofaktor** [comment]
> This feature is available in the latest version

Yeah, right, but, why have you limited the increase in the gap limit only to 100?

![Screenshot_20230524_215014_io nunchuk android_edit_1722784907549](https://github.com/nunchuk-io/nunchuk-android/assets/89636253/33158d98-60bd-47e8-b47c-ef112198944f)

**Comment by hugohn** [comment]
@twofaktor for the obvious reason: because large limits put a heavy burden on the server. We can make it so that if you connect to your own server, you can have unlimited limit.

**Comment by twofaktor** [comment]
> We can make it so that if you connect to your own server, you can have unlimited limit.

It could be a good idea, I have a high-performance Fulcrum server and never had issues on Sparrow with a 500 gap limit for example

**Comment by hugohn** [comment]
@twofaktor You are welcome! By the way just curious, did this allow you to load your BTCPayServer wallet?

**Comment by bitcoinheiro** [comment]
Not working for me... But would be great to have some sort of feedback on
what's happening - if anything is happening at all - during this scan

**Comment by bitcoinheiro** [comment]
It worked now after a while without any feedback at all that it actually
was working - lack of feedback makes dumb users like me think it failed :)
I changed the gap limit (to 80 was enough here) and pressed "Force Refresh"
- was this the correct move? Or I didn't need to hit "Force Refresh" too?

**Comment by twofaktor** [comment]
> @twofaktor You are welcome! By the way just curious, did this increase allow you to load your BTCPayServer wallet?

Yes, Nunchuck successfully loaded my BTCpay multisig wallet and was able to create a transaction using far UTXOS. Thanks! Do you know if this feature will be added to the desktop version and when?
