### ISSUE TITLE
BUG: Scan of descriptor QR from Sparrow Wallet not working

### ISSUE THREAD

**Issue by seedhammer** [nunchuk-io/nunchuk-android#14]
Nunchuk app (iOS v. 1.9.25 and Android 1.9.30) does not seem to import the descriptor exported from Sparrow Wallet.

- Open a multisig wallet in Sparrow Wallet and press the QR-icon under "Script Policy"
- Open nunchuk wallet and create a new wallet -> Recover existing wallet -> Recover via QR.
- Now try to scan the animated QR from Sparrow.

Alternatively download the descriptor as PDF - this does not scan as well:
<img width="339" alt="image" src="https://github.com/nunchuk-io/nunchuk-android/assets/93251679/9b99919b-dfc1-4499-b34a-fca602be3dfa">

Sparrow export in the UR split descriptor format. https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-005-ur.md is the QR format, https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-010-output-desc.md is the particular encoding for the descriptor.

**Comment by bakaoh** [comment]
thanks @seedhammer, currently Nunchuk app doesn't support BCR-2020-010 format, we will support it in future

**Comment by seedhammer** [comment]
Example files attached.
[1-of-2-24.zip](https://github.com/nunchuk-io/nunchuk-android/files/11608900/1-of-2-24.zip)
[2-of-3-24.zip](https://github.com/nunchuk-io/nunchuk-android/files/11608901/2-of-3-24.zip)
[3-of-5-24.zip](https://github.com/nunchuk-io/nunchuk-android/files/11608902/3-of-5-24.zip)

**Comment by bakaoh** [comment]
hi @seedhammer , i have successfully decoded the Sparrow QR and your 2-of-3, 3-of-5 example. But for 1-of-2, i receive 
```
wsh([dc567276/48'/0'/0'/2']xpub6DiYrfRwNnjeX4vHsWMajJVFKrbEEnu8gAW9vDuQzgTWEsEHE16sGWeXXUV1LBWQE1yCTmeprSNcqZ3W74hqVdgDbtYHUv3eM4W2TEUhpan)
```
which is not multi-sig descriptor, could you please provide the descriptor for that wallet so i can debug my code?

**Comment by seedhammer** [comment]
We have had the time to test your implementation.

Underneath is a 2-of-3 multisig (testnet!) wallet backed up on seedhammer with the balance BTC 0.0003735.

Test 1: Scan share 1 + 2 into Nunchuk. See balance: BTC 0.0003735
Test 1 succeeds.

Delete the wallet.

Test 2: Scan share 2 + 3 into Nunchuk. See balance: BTC 0.0
Test 2 fails.

Delete the wallet.

Test 3: Scan share 1 + 3 into Nunchuk. See balance: BTC 0.0003735
Test 3 succeeds.

Share 1:
![plate-0-side-0](https://github.com/nunchuk-io/nunchuk-android/assets/93251679/2072be27-7f77-44ff-84ad-c5e48f6e0047)

Share 2:
![plate-1-side-0](https://github.com/nunchuk-io/nunchuk-android/assets/93251679/d9ba13d7-dc1c-4323-9567-2e3f977ee584)

Share 3:
![plate-2-side-0](https://github.com/nunchuk-io/nunchuk-android/assets/93251679/79581cf8-0522-43a3-b196-988a6dfe2436)

**Comment by seedhammer** [comment]
Consider to do a Force refresh in the cases where you detect used addresses with balance 0.

**Comment by hugohn** [comment]
Great!

So we can't auto refresh, because used addresses CAN have 0 balance. It just needs to be fixed manually (it should be relatively rare anyway).

**Comment by hugohn** [comment]
We suspect that when it happens, it could be due to the fact that you delete and recover the wallet within the same session. The Electrum server/client code might have gotten confused as to whether an address has been synced or not. Try killing the app after deleting the wallet + maybe waiting a few minutes before attempting to recover it. @seedhammer

**Comment by seedhammer** [comment]
Thank you. We consider the issue resolved. 

Thanks for quick and swift processing of this issue.

**Comment by seedhammer** [comment]
Hi,

We have problems signing from the above wallet.

**Error while trying to sign a multisig tx**

1. Restore the wallet above
2. Make a tx
3. When pressing one of the Sign-buttons you get: Signer id can not empty!

![IMG_8180](https://github.com/nunchuk-io/nunchuk-android/assets/93251679/cceed237-0513-4527-bd12-ef402eedcf39)

**Comment by bakaoh** [comment]
hi @seedhammer did you recover the signer(s)?

**Comment by seedhammer** [comment]
Hi,

I recovered the wallet by pressing + -> Recover existing wallet -> Recover via QR code

I then scan 2 of the 3 SeedHammer plates.

I now see the balance and adresses. And expect to be able to create an tx.

**Comment by hugohn** [comment]
We can make the process easier by not requiring the (re)add keys step, and just allowing you to sign using unnamed/unknown keys. But that's going to be in a later release.

**Comment by hugohn** [comment]
@seedhammer try updating to the latest TestFlight build, it allows you to sign using unknown 'import' keys.

**Comment by seedhammer** [comment]
Okay - the whole idea with SeedHammer backup plates is that you don't need anything else than the quorum of plates in order to restore _and_ spend from the wallet.

Since the descriptor contains all the necessary information, there are no XPUB QR codes.

Thank you for implementing this with short notice. It seems to work.
