### ISSUE TITLE
NO way to withdraw funds?

### ISSUE THREAD

**Issue by jadiemay28** [nunchuk-io/nunchuk-android#18]
Please please help me?  
I do not see any option anywhere, nor instructions anywhere on the web, for how to withdraw the funds from my Nunchuk wallet to a bank account or PayPal.  
I am afraid this stuff is over my head, so please please if you understand how to accomplish this (what I thought would have been super simple) task can you share the steps I need to take either from the Nunchuk app or Nunchuk website?
Thank you so much in advance!

**Comment by hugohn** [comment]
Hello,
We support issues related to Bitcoin only. (Also, banks and Paypal don't have a Bitcoin wallet, AFAIK.)

**Comment by jadiemay28** [comment]
So Nunchuk can only transfer monies to another wallet, in your example a "Bitcoin wallet?"  Do you mean something like Coinbase?  I need instructions too please!
