### ISSUE TITLE
Use of private electrum server does not work over ssl

### ISSUE THREAD

**Issue by BrunswickBTC** [nunchuk-io/nunchuk-android#28]
The public electrum servers appear to work with nunchuk, but when i switch to my private electrum server, it says it cannot contact it. It works fine with bluewallet, sparrow and other wallets.

**Comment by bakaoh** [comment]
hi @BrunswickBTC , did you add `ssl://` prefix to your electrum url?

**Comment by BrunswickBTC** [comment]
No i havent had to do that before. I confirm adding ssl:// makes it work. Thank you
