### ISSUE TITLE
Google Play Services Dependency

### ISSUE THREAD

**Issue by acronymy** [nunchuk-io/nunchuk-android#3]
Each time Nunchuk Android is opened, a popup is displayed:
"No valid Google Play Services found. Cannot use FCM."
Requiring users to run proprietary and privacy-invasive Google Play Services to (presumably) provide push notifications in an open-source project is not necessary, goes against the ethos of your privacy conscious users, and impacts their trust in Nunchuk. (in my opinion)
Signal-Android (and others) has shown it is possible to have 100% reliable push notifications without any Google Play Services.

**Comment by JayceLuong** [comment]
Removed it the latest version

**Comment by acronymy** [comment]
Removed the dependency or the notification only?

Thank you. 

May 28, 2023, 07:31 by ***@***.***:
