### ISSUE TITLE
Protect wallet with PIN not working

### ISSUE THREAD

**Issue by maxirosson** [nunchuk-io/nunchuk-android#31]
There is a privacy leak when you have "Hide wallet details" and "Protect wallets with a PIN" enabled.

First, when you open the app you see the balance for a second, until it is hidden.
Second, If you tap on the wallet very quickly during that window of time, you can enter to the wallet details without entering the PIN.

Android app v1.9.33

Video reproducing the bug attached

https://github.com/nunchuk-io/nunchuk-android/assets/1051983/e5a6cb4c-e9d2-4c0f-b8a7-7f2e0abc94fc

**Comment by hugohn** [comment]
Thanks for reporting @maxirosson . We’ll investigate.

**Comment by maxirosson** [comment]
Nice. Thanks. My suggestion is you should hide the balance by default and only show it when the preference is loaded and says it must be visible. It seems you could be doing the opposite.

**Comment by hugohn** [comment]
Fixed in the latest version (1.9.33). Could you give it a try? @maxirosson 
https://play.google.com/store/apps/details?id=io.nunchuk.android
