### ISSUE TITLE
Add release section to SigningConfig that load values from file properties to avoid build failure

### ISSUE THREAD

**Issue by emanuelb** [nunchuk-io/nunchuk-android#4]
Compiling the app with `./gradlew assemble` or `./gradlew assembleDebug` or `./gradlew assembleRelease`  
will return error:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/appuser/app/nunchuk/nunchuk-android/nunchuk-app/build.gradle' line: 63

* What went wrong:
A problem occurred evaluating project ':nunchuk-app'.
> Could not get unknown property 'release' for SigningConfig container of type org.gradle.api.internal.FactoryNamedDomainObjectContainer.
```

cause in:
https://github.com/nunchuk-io/nunchuk-android/blob/88fb4d0bfc26915044bfc543e71c7e4141d2b479/nunchuk-app/build.gradle#L63

it mention release section in SigningConfig that doesn't exists
https://github.com/nunchuk-io/nunchuk-android/blob/88fb4d0bfc26915044bfc543e71c7e4141d2b479/nunchuk-app/build.gradle#L43-L50

Fix:

add release section to SigningConfig, it can load the values from reading properties file.
examples how it's done in other projects:
1. https://github.com/EdgeApp/edge-react-gui/blob/ab54753be5b8f0591b0e4767db7d14d5db3600ce/android/app/build.gradle#L233-L240
2. https://github.com/Blockstream/green_android/blob/ccce7387ab97f2c8392b9d9c14a1896ccddf6740/green/build.gradle#L12-L26  https://github.com/Blockstream/green_android/blob/ccce7387ab97f2c8392b9d9c14a1896ccddf6740/green/build.gradle#L51-L59

**Comment by JayceLuong** [comment]
Updated, please check again. Thanks

**Comment by emanuelb** [comment]
Closing issue as it's fixed in https://github.com/nunchuk-io/nunchuk-android/commit/140ff82819243a499f7ebe82926c1911a90be698
