### ISSUE TITLE
Not all keys are displayed

### ISSUE THREAD

**Issue by bitcoinlizard** [nunchuk-io/nunchuk-android#41]
I am operating in Guest Mode and have uploaded 3 keys.  The upload process is successful and I am able to create a multisig wallet using all 3 or the keys however at the main Nunchuk screen showing wallets and keys only 2 of the 3 keys are displayed.  
See the main screen:
![main-screen](https://github.com/nunchuk-io/nunchuk-android/assets/75000074/97408c78-e528-4435-9f6d-91eb7652dd79)

And they keys included in a wallet:
![wallet](https://github.com/nunchuk-io/nunchuk-android/assets/75000074/4fee3498-6f5a-4aa8-bea0-653acdc1181f)

**Comment by hugohn** [comment]
Try scrolling right. The keys list on Home is horizontally scrollable.
