### ISSUE TITLE
Cannot import key from QR Code Hardware Wallet at ver 1.9.38

### ISSUE THREAD

**Issue by AndyVineyard** [nunchuk-io/nunchuk-android#42]
Cannot import key from QR Code Hardware Wallet at ver 1.9.38, but trying at 1.9.37 works fine. After scanning Nunchuk shows blank xpub like nothing happens. At 1.9.37 Nunchuk can scan and showing xpub key

**Comment by hugohn** [comment]
Should be fixed now in latest release. Please reopen if issue still persists.
