### ISSUE TITLE
[BUG] Scan of singlesig descriptors from SeedHammer doesn't work

### ISSUE THREAD

**Issue by seedhammer** [nunchuk-io/nunchuk-android#45]
Hi,

Attached is 3 examples - 1, and 2 does not scan on iOS. 3 does, but without the percentage indication:
- Singlesig 12 words:
![plate-0-side-front](https://github.com/nunchuk-io/nunchuk-android/assets/93251679/00b83ed5-7332-406d-8d48-33f3b4ee7196)
- Singlesig 24 words:
![plate-0-side-front](https://github.com/nunchuk-io/nunchuk-android/assets/93251679/36b28729-2f4d-48eb-94ad-34dfd6e53183)
- Multisig 3-of-5:
![plate-0-side-front](https://github.com/nunchuk-io/nunchuk-android/assets/93251679/6640d26a-cb47-44ad-bde9-cf62b9ae0dde)
![plate-1-side-front](https://github.com/nunchuk-io/nunchuk-android/assets/93251679/d9f906ef-89bb-4ce2-8959-4675634f5d03)
![plate-2-side-front](https://github.com/nunchuk-io/nunchuk-android/assets/93251679/74f04c36-a716-4b18-a7e9-b190ceb61568)
![plate-3-side-front](https://github.com/nunchuk-io/nunchuk-android/assets/93251679/a815a852-a19b-4ead-b917-cbcd1f9d8ce3)
![plate-4-side-front](https://github.com/nunchuk-io/nunchuk-android/assets/93251679/d44efd2f-2941-4b31-a3b9-d8e2b1ecb453)

**Comment by hugohn** [comment]
@seedhammer Thanks for reporting guys. We've identified the issue for singlesig QR - the singlesig path doesn't include `m` notation.

Fix is incoming.

**Comment by hugohn** [comment]
Fixed in latest release.
