### ISSUE TITLE
Bug: Export of testnet multisig dosn't work on Sparrow nor SeedHammer

### ISSUE THREAD

**Issue by seedhammer** [nunchuk-io/nunchuk-android#46]
Hi,

Looks like this bug-report actually is a Nunchuk bug, since it doesn't scan in SeedHammer software as well:

https://github.com/sparrowwallet/sparrow/issues/1272

If true, I will delete the above report and let this ticket stay.

**Comment by hugohn** [comment]
@seedhammer FYI, exporting the wallet configuration  via BC-UR2 encoding is now possible with the latest mobile versions. Cheerd.
