### ISSUE TITLE
Missing sources for latest release 1.9.23 on google-play

### ISSUE THREAD

**Issue by emanuelb** [nunchuk-io/nunchuk-android#5]
The version in google-play is: 1.9.23 Updated: Dec 29, 2022 versionCode: '194'
https://play.google.com/store/apps/details?id=io.nunchuk.android

While currently code in repo is only 1 commit (besides the fix to FTBFS issue I opened) from Nov 17 https://github.com/nunchuk-io/nunchuk-android/commit/88fb4d0bfc26915044bfc543e71c7e4141d2b479

Compiling the code in the first commit will create APK with `versionCode: '191'` and `versionName: 1.9.21`

Please publish the code for latest 1.9.23 version on google-play, and in future ensure that code is published to this repo before apk generated from it is released to google-play.

**Comment by JayceLuong** [comment]
Published latest source code
