### ISSUE TITLE
Latest release APK 1.9.43 shows version 1.9.42

### ISSUE THREAD

**Issue by svrgnty** [nunchuk-io/nunchuk-android#51]
The APK in the latest release, [1.9.43](https://github.com/nunchuk-io/nunchuk-android/releases/tag/android.1.9.43), once installed, shows version 1.9.42

![461f4dfc-f3aa-4160-9a03-aee02664b9f4](https://github.com/nunchuk-io/nunchuk-android/assets/120567975/26128d6d-47b7-46ab-8c1e-d9fcc0e4c14a)
![d9c3a5c8-3b72-424e-bac5-28e5abd313ea](https://github.com/nunchuk-io/nunchuk-android/assets/120567975/e67a8d6c-4dc8-4f06-9918-6b275e731230)

**Comment by JayceLuong** [comment]
Hi, it has been resolved. please check again. Thank you for reporting it
