### ISSUE TITLE
Request for Signed Releases and Hashes

### ISSUE THREAD

**Issue by crimsonleaf363** [nunchuk-io/nunchuk-android#53]
There is currently no way for us to validate the authenticity of the downloaded apk outside of centralized app stores. Please provide an added layer of security for users who can't or won't build your app from source. I hope that you will implement this for future releases. Thank you for continuing to develop and maintain this app.

**Comment by JayceLuong** [comment]
Hi @crimsonleaf363 We have been provided with both signed releases and hashes. Please check again. https://github.com/nunchuk-io/nunchuk-android/releases/tag/android.1.9.45
