### ISSUE TITLE
Can not add Portal device key, loops back to 'Add Portal' screen after 'Ready to Scan'

### ISSUE THREAD

**Issue by remyers** [nunchuk-io/nunchuk-android#55]
Android version: 14
Device: Pixel 7a
Nunchuk app version: 1.9.48

Repo steps:

- [ ] 1.     install app (fresh install)
- [ ] 2.     Unassisted wallet
- [ ] 3.     select "Create a hot wallet now" OR "I'll explore on my own" (tried both)
- [ ] 4.     Keys -> + (add key)
- [ ] 5.     Add NFC key -> Add Portal
- [ ] 6.     see "Add Portal" screen and press Continue (while not touching Portal device)
- [ ] 7.     see "Read to Scan" dialog
- [ ] 8.     put phone on Portal device
- [ ] 9.     see Welcome screen on Portal device AND return to "Add Portal" screen
- [ ] 10.     loops back to step 7

I turned on debug log but it's empty after these steps. Is there any other way I can help you debug this issue?

**Comment by hugohn** [comment]
Wow that was fast Richard!

Can you check what Portal firmware version are you running? There were a few issues on older firmwares, so let’s make sure you’re running the latest first.

**Comment by hugohn** [comment]
We think it’s a Proguard issue when uploading to the Play Store. Hang on @remyers .

**Comment by hugohn** [comment]
Confirmed that it was Proguard. We have pushed a fix. Can you update the app and try again? @remyers

**Comment by remyers** [comment]
Yes, version 1.9.48 (239) now let's me add a key.

I followed the dialogs and Portal scrolled 24 words and confirmed the pin, but was then stuck at "Loading" for a long time.

I cut power and when I connected again Portal displays "LOCKED".

If I try to add the Portal again as a key I see a "tag was lost" message on Nunchuk.

I'll follow up with TwentyTwo devices to see if they have any advice.

**Comment by remyers** [comment]
Could Proguard still be effecting other dialogs? I can now use and add the key but it seems like it's sometimes jumping to the wrong dialog when I scan the Portal device. I'll try to get better repo steps when I have time, but we can close this for now.
