### ISSUE TITLE
PIN dialog labels confusing

### ISSUE THREAD

**Issue by svrgnty** [nunchuk-io/nunchuk-android#56]
I find the language around the PINs could be confusing for users.

- If you set a PIN for wallet access, the unlock dialog label is "Enter your PIN"
- If you use a device with a pin (e.g. Portal), the unlock dialog label is "Enter PIN"

Both are very similar and it could be unclear what PIN is needed. I would suggest changing the labels to something like:

- wallet PIN: "Enter your wallet PIN" or "Enter wallet PIN"
- device PIN: "Enter your device PIN" or "Enter device PIN"

**Comment by hugohn** [comment]
We’re changing it to “Device password” in the next release (ETA ~ in a couple of days) for Portal. Some bug fixes/improvements for Portal as well.
