### ISSUE TITLE
Cannot input the same key with NFC after deleted via QR code

### ISSUE THREAD

**Issue by AndyVineyard** [nunchuk-io/nunchuk-android#61]
I noticed after I input the key via QR code (keystone) and deleted it , then want to add the SAME key via NFC (Coldcard), screen not responding just back to the tutorial for connecting the coldcard with NFC, but if add with QR code it's added like normal again

**Comment by hugohn** [comment]
what do you mean by the same key? the seem seed phrase? you put the same seed phrase in both Keystone and Coldcard?

**Comment by AndyVineyard** [comment]
Yeah same seed phrase and passphrase both keystone & coldcard

**Comment by hugohn** [comment]
You likely have an issue with NFC scanning or hardware, not an issue with the code.

The Coldcard mk4 has a relatively weak NFC signal and is highly sensitive to positioning. You might also have to hold your phone in position for a while. Please check out the below video from Coinkite and a related thread to see how you could improve the NFC scanning success rate.
https://twitter.com/nunchuk_io/status/1575649919280369664
