### ISSUE TITLE
Cannot import key from Coldcard Q through NFC

### ISSUE THREAD

**Issue by ralessi** [nunchuk-io/nunchuk-android#62]
Hi,

My issue is somewhat similar to #55.

On the Coldcard Q, I use the newly featured function `Export Wallet -> Nunchuk`. All seems to be going smoothly until the phone beeps and vibrates. But the key is not imported and I am brought back to the previous screen ("Coldcard NFC tip").

I tried to read the Coldcard [with this simple app](https://f-droid.org/packages/se.anyro.nfc_reader), and I think it worked. At least, I can see the json file on the screen just after the phone beeps and vibrates.

I own a Pixel 7a which I use with GrapheneOS.

Thank you for your help!

**Comment by ralessi** [comment]
Correction: [I used this app](https://f-droid.org/en/packages/com.github.muellerma.nfcreader/) to read the Coldcard Q.

**Comment by hugohn** [comment]
Thanks for reporting @ralessi . We've confirmed the issue. Will issue a fix soon.

**Comment by ralessi** [comment]
Great, thank you @hugohn !

**Comment by ralessi** [comment]
With the recent releases of the application I believe this issue is fixed. Thank you!
