### ISSUE TITLE
Testnet not syncing?

### ISSUE THREAD

**Issue by debben** [nunchuk-io/nunchuk-android#72]
On both the android and desktop versions of Nunchuk I've tried multiple testnet wallets which show no transactions. I've tried with both the default electrum servers `testnet.nunchuk.io:50001` and with other testnet electrum servers. The UI shows `Online(Testnet)`. I've tried going into the wallet config and using the "Force refresh" option but still no transactions show up. When I export the wallet descriptor into another application like Sparrow, there are transactions showing for those testnet wallets.

**Comment by hugohn** [comment]
Hello, we’ve officially switched to testnet4 since a couple of releases ago.

If you want to continue using testnet3, you can point to a public Electrum testnet3 server.
