### ISSUE TITLE
Total balance doesn't display with Dark Mode

### ISSUE THREAD

**Issue by slcw** [nunchuk-io/nunchuk-android#73]
There seems to be a bug with the total balance display when the dark theme is applied. I have my Nunchuk set to display the total balance of all wallets, which displays at the bottom of the home screen. It works fine with with the light theme, however when the dark theme is enabled, there's just a white band on the bottom where the total normally is.

**Comment by Blaze8988** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by slcw** [comment]
I'm aware of what GitHub Issues is for, and my post is related to a bug that has surfaced in the latest release (v1.9.56). Specifically, a bug related to the new dark theme, and the option to display the total balance on the home screen.

**Comment by hugohn** [comment]
Please ignore the comment by @Blaze8988 . It's a scammer. Deleted and reported.

**Comment by hugohn** [comment]
Fixed in the latest version.
