### ISSUE TITLE
How to enable biometric login?

### ISSUE THREAD

**Issue by remcoros** [nunchuk-io/nunchuk-android#75]
Just downloaded the new version, I see the option "Protect wallets with Fingerprint", but the label and checkbox are grayed out and disabled. Cannot click on it.

Checked the android permissions to see if I should give the app access to Biometric devices, but it doesn't have a settable permission like that.

Am I missing something?

**Comment by hugohn** [comment]
Hey @remcoros 
Biometric login currently doesn't work if you use Guest mode or have a Primary Key account.

**Comment by remcoros** [comment]
thanks for the clarification 👍
