### ISSUE TITLE
Andoid app chrashes a lot

### ISSUE THREAD

**Issue by Funman2** [nunchuk-io/nunchuk-android#8]
Hey, my setup is Nunchuk collab multisig wallet 2 android phones ( Android 8 and Android 9 Software Version), one dektop app.
The Android app keeps crashing when opening and when trying to sign in to primary accounts. The crashes happen multiple times, then eventually it works. 
It´s a little better after reinstalling but not optimal. Then after some time of usage the crashing intensifies.

**Comment by JayceLuong** [comment]
Hi thank you for reporting the bug, could you send me a video to help me investigate the crash?

**Comment by JayceLuong** [comment]
You use test net or main net?

**Comment by Funman2** [comment]
Main net.



Von meinem/meiner Galaxy gesendet



-------- Ursprüngliche Nachricht --------
Von: Jayce ***@***.***>
Datum: 17.01.23 14:01 (GMT+01:00)
An: nunchuk-io/nunchuk-android ***@***.***>
Cc: Funman2 ***@***.***>, Author ***@***.***>
Betreff: Re: [nunchuk-io/nunchuk-android] Andoid app chrashes a lot (Issue #8)


You use test net or main net?

**Comment by JayceLuong** [comment]
Could you try [this APK](https://drive.google.com/file/d/1VNDjtjgmmk5avZLhydCeXIQXFsFQKsFY/view?usp=share_link )?

**Comment by Funman2** [comment]
Will do tonight! Thank you, just have to get hold of my private keys first...

**Comment by Funman2** [comment]
> Could you try [this APK](https://drive.google.com/file/d/1VNDjtjgmmk5avZLhydCeXIQXFsFQKsFY/view?usp=share_link)?

Yes this 'development's app works totally stable. 
I guess this is the honey badger version somehow? Since when signed in I got 3 different chats popping up, one called 'Server Notices', one named ' Nunchuk Sync' and one regular with account fingerprint as a name. (See pictures)
![Screenshot_20230117-220732_Development](https://user-images.githubusercontent.com/105175715/213013872-ce341e34-4248-4e33-820a-8d00aca549ad.jpg)
![Screenshot_20230117-220739_Development](https://user-images.githubusercontent.com/105175715/213013881-841b602e-b2ab-4e3c-b704-4d8115ba5453.jpg)
![Screenshot_20230117-220751_Development](https://user-images.githubusercontent.com/105175715/213013885-e30bde9b-4ee8-496d-8e46-823f8e4caa98.jpg)

**Comment by JayceLuong** [comment]
Please ignore it, it only visible in debug version not production version

**Comment by JayceLuong** [comment]
we will make the update today, Please check new version from play store and close it. again Thank for reporting

**Comment by Funman2** [comment]
Hey, today the update came through, but now with my existing primary account, the Nunchuk android app hangs up on signing in if i am online but not connected to my electrum server of my node, it takes about 2 Minutes to sign in or completely does not sign in...when my tailscale is connected it signs in immediately. This behavior is new and was not like that in prior versions. When i was online i could sign in, then afterward i could start tailscale vpn service and the blockchain sync would go to syncing status then online. will share video

**Comment by Funman2** [comment]
Another small possible bug I detected: When trying to sign out all devices from settings it does not work in android app, also way too many devices are listed. 
Second thing I found, when canceling a signed transaction it only synced with one other android device, the other android still has the transaction as 'ready to broadcast'
![Screenshot_20230119-121221_Nunchuk](https://user-images.githubusercontent.com/105175715/213429227-974cd4db-0515-412e-afe8-9c56e7d11df3.jpg)

**Comment by JayceLuong** [comment]
we are checking issue number 2 and 3. For the fist one I believe we have to wait to connected electrum server first

**Comment by JayceLuong** [comment]
Regarding sync feature, it would be nice if you try on assisted wallet test net with Honey Badger plan, we no longer maintain previous sync by enable from Setting. we have new one for Premium User

**Comment by Funman2** [comment]
> we are checking issue number 2 and 3. For the fist one I believe we have to wait to connected electrum server first

Ok ... it's strange though since in prior versions I could log in and then it would just say offline. When I connect my Tailscale  VPN to electrum server it worked switch to online. 
But now I can't even log on so if my personal electrum would be down i could not even log in to switch to nunchuk's backend server for electrum then...

**Comment by Funman2** [comment]
Hey so after latest android update(nunchuk 1.9.25) I can not log in at all anymore with my primary key account. I just get error message 'handshake failed' even if my tailscale is connected (see screenshot) even if I uninstall and reinstall and try again to set up my primary account it says ' account not found' 
If it stays like this Nunchuk is not usable for me anymore. :-(

**Comment by Funman2** [comment]
Hey, maybe forget about my last issue, I think there must have been a server side issue, since now, one hour later it all works fine again!

**Comment by JayceLuong** [comment]
> Another small possible bug I detected: When trying to sign out all devices from settings it does not work in android app, also way too many devices are listed. Second thing I found, when canceling a signed transaction it only synced with one other android device, the other android still has the transaction as 'ready to broadcast' ![Screenshot_20230119-121221_Nunchuk](https://user-images.githubusercontent.com/105175715/213429227-974cd4db-0515-412e-afe8-9c56e7d11df3.jpg)

Now we don't clear session immediately. For the security reason you need to go your email and confirm the action

**Comment by Funman2** [comment]
Ok but since it is a primary key account there is no email address associated...

**Comment by Funman2** [comment]
Still not working for primary account
