### ISSUE TITLE
Adding a second primary account in android app

### ISSUE THREAD

**Issue by Funman2** [nunchuk-io/nunchuk-android#9]
When trying to add a second primary account on android app it is quite tricky, since you could not add a second account once primary is set up, it only shows you the option and allows you to log in to an existing key, but it displays no option to add another existing primary account.
Only when approaching this process after logging out or from guest mode it worked somehow sometimes...

**Comment by Funman2** [comment]
Works now!

**Comment by JayceLuong** [comment]
Thank you @Funman2
